# Generated by Django 3.2.18 on 2023-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='father_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='surname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
